package com.telen.easylineup.domain.model

enum class DomainErrors {
    SAVE_PLAYER_FIELD_POSITION_FAILED,
    DELETE_PLAYER_FIELD_POSITION_FAILED,
    LIST_AVAILABLE_PLAYERS_EMPTY,
    SAVE_BATTING_ORDER_FAILED,
    DELETE_LINEUP_FAILED,
    SAVE_LINEUP_MODE_FAILED,
    UPDATE_PLAYERS_WITH_LINEUP_MODE_FAILED,
    GET_TEAM_FAILED,
    NEED_ASSIGN_PITCHER_FIRST,
    DP_OR_FLEX_NOT_ASSIGNED,
    INVALID_PLAYER_NAME,
    INVALID_PLAYER_LICENSE,
    INVALID_PLAYER_NUMBER,
    INVALID_PLAYER_ID,
    INVALID_LINEUP_NAME,
    INVALID_TOURNAMENT_NAME,
    CANNOT_EXPORT_DATA
}