import java.nio.charset.StandardCharsets

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        appVersionName = "2.0.0"
        appVersionCode = 2_00_00_04
        minVersion = 21
        targetVersion = 35
        compileVersion = 35
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.googleServices) apply false
    alias(libs.plugins.navigation) apply false
    alias(libs.plugins.sonarqube) apply false
    alias(libs.plugins.dependencyCheck) apply false
    alias(libs.plugins.appdistribution) apply false
    alias(libs.plugins.crashlytics) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.kotlin.ksp) apply false
}

apply from: 'sonar.gradle'
apply from: 'detekt.gradle'

spotless {
    encoding = StandardCharsets.UTF_8
    java {
        target("**/*.java")
        targetExclude("**/build/**")
        importOrder()
        removeUnusedImports()
        googleJavaFormat().aosp()
        formatAnnotations()
        trimTrailingWhitespace()
        endWithNewline()
    }
    kotlin {
        target("**/*.kt")
        targetExclude("**/build/**")
        diktat().configFile("$rootDir/Formatting.yml")
        trimTrailingWhitespace()
        endWithNewline()
    }
}