plugins {
    alias(libs.plugins.android.library)
}

repositories {
    maven { url 'https://jitpack.io' }
}

def sonarPropertiesFile = rootProject.file("sonar.properties")
def sonarProperties = new Properties()
if (sonarPropertiesFile.exists()) {
    sonarProperties.load(new FileInputStream(sonarPropertiesFile))
}

android {
    compileSdkVersion compileVersion

    defaultConfig {
        minSdkVersion minVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }

    flavorDimensions 'version'
    productFlavors {
        dev {
            dimension 'version'
        }
        prod {
            dimension 'version'
        }
        demo {
            dimension 'version'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.all {
            jacoco {
                includeNoLocationClasses = true
                excludes = ['jdk.internal.*']
            }
        }
        targetSdk { version = release(targetVersion) }
    }
    namespace 'com.telen.easylineup.domain'
    lint {
        abortOnError false
        targetSdk targetVersion
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    testImplementation libs.tests.junit
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin

    implementation libs.rx.java
    implementation libs.gson
    implementation libs.koin
    implementation libs.documentFile
    implementation libs.android.core
}

apply from: '../jacoco.gradle'