plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.navigation)
    alias(libs.plugins.googleServices)
    alias(libs.plugins.appdistribution)
    alias(libs.plugins.crashlytics)
}

def keystorePropertiesFile = rootProject.file("keystore-upload.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
else {
    // Otherwise read from environment variables, this happens in CI
    keystoreProperties.setProperty("storeFile", "../telen.release.jks")
    keystoreProperties.setProperty("storePassword", "${System.getenv('KEYSTORE_PASSWORD')}")
    keystoreProperties.setProperty("keyAlias", "${System.getenv('KEY_ALIAS')}")
    keystoreProperties.setProperty("keyPassword", "${System.getenv('KEY_PASSWORD')}")
    keystoreProperties.setProperty("debug.storeFile", "../telen.debug.jks")
    keystoreProperties.setProperty("debug.storePassword", "${System.getenv('DEBUG_KEYSTORE_PASSWORD')}")
    keystoreProperties.setProperty("debug.keyAlias", "${System.getenv('DEBUG_KEY_ALIAS')}")
    keystoreProperties.setProperty("debug.keyPassword", "${System.getenv('DEBUG_KEY_PASSWORD')}")
}

android {
    namespace "com.telen.easylineup"
    compileSdkVersion compileVersion
    defaultConfig {
        applicationId "com.telen.easylineup"
        minSdkVersion minVersion
        targetSdkVersion targetVersion
        versionCode appVersionCode
        versionName appVersionName
        testInstrumentationRunner "com.telen.easylineup.EasylineupAndroidTestRunner"
        vectorDrawables.useSupportLibrary true
        buildConfigField "Boolean", "UseBetaTool", "true"
        firebaseAppDistribution {
            serviceCredentialsFile="easylineup-services.json"
            releaseNotesFile="releasenotes.txt"
            testersFile="testers.txt"
        }
    }

    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'

    flavorDimensions 'version'

    signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }

        debug {
            storeFile file(keystoreProperties['debug.storeFile'])
            storePassword keystoreProperties['debug.storePassword']
            keyAlias keystoreProperties['debug.keyAlias']
            keyPassword keystoreProperties['debug.keyPassword']
        }
    }

    productFlavors {
        dev {
            dimension 'version'
            applicationIdSuffix = ".dev"
            matchingFallbacks = ['prod']
            buildConfigField "String", "reportStorageRoot", "\"reports.dev\""
        }
        prod {
            dimension 'version'
            matchingFallbacks = ['prod']
            buildConfigField "String", "reportStorageRoot", "\"reports.prod\""
        }
        demo {
            dimension 'version'
            applicationIdSuffix = ".demo"
            matchingFallbacks = ['demo']
            buildConfigField "String", "reportStorageRoot", "\"reports.demo\""
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
            versionNameSuffix "-debug"
            firebaseCrashlytics {
                // If you don't need crash reporting for your debug build,
                // you can speed up your build by disabling mapping file uploading.
                mappingFileUploadEnabled false
            }
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt', 'META-INF/ASL2.0']
        }
    }


    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation libs.kotlin
    implementation libs.annotation

    // Testing-only dependencies
    androidTestImplementation(libs.tests.espresso) {
        exclude group: "com.google.protobuf"
    }
    androidTestImplementation files('libs/cloudtestingscreenshotter_lib.aar')
    androidTestImplementation libs.tests.rxIdler
    androidTestImplementation libs.tests.uiAutomator
    androidTestImplementation libs.tests.screengrab
    androidTestImplementation(libs.tests.barista) {
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
    }

    testImplementation libs.tests.junit

    ////////// ANDROID X //////////

    implementation libs.activity
    implementation libs.fragment
    implementation libs.recyclerView
    implementation libs.preference
    implementation libs.constraintlayout

    // ViewModel and LiveData
    implementation libs.viewmodel
    implementation libs.livedata

    implementation libs.multidex
    implementation libs.navigation.runtime
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.documentFile
    implementation libs.splashscreen
    implementation libs.android.core

    ////////// GOOGLE //////////

    implementation libs.material
    implementation libs.gson
    implementation platform(libs.firebase)
    implementation libs.firebase.crashlytics.ktx
    implementation libs.firebase.analytics.ktx
    implementation libs.firebase.auth.ktx
    implementation libs.firebase.firestore.ktx
    implementation libs.firebase.storage.ktx
    implementation libs.firebase.config.ktx
    implementation(libs.firebase.appcheck.playintegrity)
    implementation(libs.firebase.appcheck.ktx)

    ////////// PRIVATE //////////

    implementation project(path: ':repository')
    implementation project(path: ':domain')
    implementation libs.androidTable

    ////////// OTHERS //////////

    implementation libs.timber
    implementation libs.rx.android
    implementation libs.mpAndroidChart
    implementation libs.picasso
    implementation libs.rounedImage
    implementation libs.koin
    implementation libs.taptaptarget
    implementation libs.dexter
    implementation libs.licenser
    implementation libs.colorPicker

    // only debug libraries
//    debugImplementation "com.squareup.leakcanary:leakcanary-android:$leakcanaryVersion"
}

apply from: '../jacoco.gradle'
apply from: '../dependency-check.gradle'