plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.ksp)
    alias(libs.plugins.room)
}

android {
    compileSdkVersion compileVersion

    defaultConfig {
        minSdkVersion minVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    flavorDimensions 'version'

    productFlavors {
        prod {
            dimension 'version'
            buildConfigField("boolean", "usePrefilledDatabase", "false")
        }

        demo {
            dimension 'version'
            buildConfigField("boolean", "usePrefilledDatabase", "true")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    namespace 'com.telen.easylineup.repository'
    lint {
        abortOnError false
        targetSdk targetVersion
    }
    buildFeatures {
        buildConfig true
    }
    room {
        schemaDirectory("$projectDir/schemas")
    }
    testOptions {
        targetSdk { version = release(targetVersion) }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.room.ktx
    ksp libs.room.compiler
    implementation libs.room.rxjava3
    implementation libs.rx.java
    implementation libs.koin
    implementation libs.timber

    implementation project(path: ':domain')
}