package com.telen.easylineup.domain.usecases.exceptions

class NameEmptyException: Exception()
class LineupNameEmptyException: Exception()
class TournamentNameEmptyException: Exception()
class NeedAssignPitcherFirstException : Exception()
class NotExistingPlayer: Exception()
class NeedAssignBothPlayersException : Exception()
class SamePlayerException: Exception()
class FirstPositionEmptyException: Exception()
class InvalidEmailException: Exception()
class InvalidPhoneException: Exception()
class UnauthorizedToMove: Exception()
class AlreadyExistingTournamentException: Exception()
class TournamentNullException: Exception()