# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

fastlane_version "2.68.0"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_android_app(task: "assembleRelease")

    # upload to Beta by Crashlytics
    crashlytics(
        api_token: ENV["FABRIC_API_TOKEN"],
        build_secret: ENV["FABRIC_BUILD_SECRET"],
        emails: ENV["FABRIC_TESTER_EMAILS"]
    )
  end
end
