# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

fastlane_version "2.68.0"

default_platform(:android)

platform :android do

    desc "Deploy to Alpha"
    lane :deploy_to_alpha do
        upload_to_play_store(track: 'alpha', aab: 'app/build/outputs/bundle/prodRelease/app-prod-release.aab')
    end

    desc "Deploy to Beta"
    lane :deploy_to_beta do
        upload_to_play_store(track: 'beta', apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
    end

    desc "Deploy to Production"
    lane :deploy_to_production do
        upload_to_play_store(track: 'production', apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
    end

    lane :build_for_screengrab do
        capture_android_screenshots(
            locales: ["en-US"],
            clear_previous_screenshots: true,
            app_apk_path: "app/build/outputs/apk/demo/debug/app-demo-debug.apk",
            tests_apk_path: "app/build/outputs/apk/androidTest/demo/debug/app-demo-debug-androidTest.apk"
        )
    end
end
