# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

fastlane_version "2.68.0"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Runs tests with usage of emulator plugin"
  lane :automation_integrationTests do

    build_android_app(
      task: 'assembleDemo',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assembleDemoDebug',
      build_type: 'AndroidTest'
    )

    desc "Build debug and test APK for screenshots"
    automated_test_emulator_run(
      AVD_setup_path: "./AVD_config.json",
      AVD_path: "~/Library/Android/sdk/tools/bin/avdmanager",
      SDK_path: "~/Library/Android/sdk",
      shell_task: "fastlane build_for_screengrab"
    )
  end

  lane :build_for_screengrab do
    capture_android_screenshots(
      locales: ["en-US"],
      clear_previous_screenshots: true,
      app_apk_path: "app/build/outputs/apk/demo/debug/app-demo-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/demo/debug/app-demo-debug-androidTest.apk"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_android_app(task: "assembleRelease")

    # upload to Beta by Crashlytics
    crashlytics(
        api_token: ENV["FABRIC_API_TOKEN"],
        build_secret: ENV["FABRIC_BUILD_SECRET"],
        emails: ENV["FABRIC_TESTER_EMAILS"]
    )
  end
end
